version: "3.9"
services:
  # web과 redis 두가지 service 정의
  # service - web
  web:
    # build from the Dockerfile in current directory
    build: .
    # binds the containser and the host machine to the exposed port, 5000
    ports:
      - "5000:5000"
    # mount the project directory (./) on the host to /code inside the container
    volumes:
      - .:/code
    # set the FLASK_ENV environment variable to development
    environment:
      FLASK_ENV: development
  # service - redis 
  redis:
    # use a public Redis image pulled from the Docker Hub registry
    image: "redis:alpine"