version: "3.9"
services:
  # proj service 정의
  proj:
    # build from the Dockerfile in current directory
    build: .

    # binds the containser and the host machine to the exposed port, 5000
    # ports:
    #   - "5000:5000"

    # mount the project directory (./) on the host to /usr/app inside the container
    volumes:
      - .:/usr/app

    # set the FLASK_ENV environment variable to development
    # environment:
    #   FLASK_ENV: development