version: "3.9"
services:
  db:
    image: mariadb
    restart: always
    ports:
      - 3306:3306
    volumes:
      - ./db/maria/data:/var/lib/mysql
    env_file: ./db/.env
    environment:
      TZ: Asia/Seoul